select_origin: directory
files_origin: ./fiches
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: false
focus_max: 2
record_types:
  undefined:
    fill: "#a7a0a0"
    stroke: "#a7a0a0"
  ressource:
    fill: "#ff5733"
    stroke: "#ff5733"
  enseignant:
    fill: "#33c4ff"
    stroke: "#33c4ff"
  projet:
    fill: "#ff33cc"
    stroke: "#ff33cc"
  SAé:
    fill: "#33ff57"
    stroke: "#33ff57"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  o:
    stroke: simple
    color: "#e01f1f"
  g:
    stroke: simple
    color: "#000000"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 6
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 10
node_size_min: 2
attraction_force: 75
attraction_distance_max: 250
attraction_vertical: 0.1
attraction_horizontal: 0.1
views: {}
chronological_record_meta: created
record_metas: []
title: BUT Infonum 3
author: Olivier Le Deuff
description: Contenus de formation du BUT infonum 3.
keywords: []
link_symbol: →
csl: ""
bibliography: ""
csl_locale: ""
css_custom: "./but3.css"
devtools: false
lang: fr
stroke: null
